CREATE TABLE Product (
  id INT PRIMARY KEY AUTO_INCREMENT,
  brand_id INT,
  category_id INT,
  name VARCHAR(255),
  description TEXT,
  img_preview VARCHAR(255),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE Category (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE Brand (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE Variation (
  id INT PRIMARY KEY AUTO_INCREMENT,
  product_id INT,
  name VARCHAR(255),
  SKU VARCHAR(255),
  qty_in_stock INT,
  import_price INT,
  sale_price INT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE `Option` (
  id INT PRIMARY KEY AUTO_INCREMENT,
  product_id INT,
  name VARCHAR(255),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE Option_value (
  id INT PRIMARY KEY AUTO_INCREMENT,
  option_id INT,
  value VARCHAR(255),
  description TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE Combination (
  id INT PRIMARY KEY AUTO_INCREMENT,
  option_value_id INT,
  variation_id INT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE ListImg (
  id INT PRIMARY KEY AUTO_INCREMENT,
  variation_id INT,
  url VARCHAR(255),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE `User` (
  id INT PRIMARY KEY AUTO_INCREMENT,
  user_name VARCHAR(255),
  email VARCHAR(255),
  password VARCHAR(255),
  avatar VARCHAR(255),
  role INT,
  verifyEmail INT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE CartItem (
  id INT PRIMARY KEY AUTO_INCREMENT,
  variation_id INT,
  user_id INT,
  quantity INT,
  active BOOLEAN,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE `Order` (
  id INT PRIMARY KEY AUTO_INCREMENT,
  user_id INT,
  state INT,
  customer_name VARCHAR(255),
  address VARCHAR(255),
  phone_number VARCHAR(255),
  note TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE OrderItem (
  id INT PRIMARY KEY AUTO_INCREMENT,
  order_id INT,
  avatar VARCHAR(255),
  name VARCHAR(255),
  price INT,
  quantity INT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE Rating (
  id INT PRIMARY KEY AUTO_INCREMENT,
  product_id INT,
  user_id INT,
  star INT,
  comment TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
